import { MenuItem } from './types';
// FIX: Removed 'Building' and 'HardDrive' from imports as 'Building' is not exported and both were unused.
import { 
  Users, Briefcase, PlusCircle, PenSquare, BookOpen, BarChart2, User, 
  Settings, BotMessageSquare, GraduationCap, DollarSign, CalendarDays, Award
} from './components/icons/Icons';

export const menuItems: MenuItem[] = [
  { name: 'Ardayda', icon: Users, path: 'ardayda', submenus: [
      { name: 'Arday Wareejin', path: 'arday-wareejin' },
      { name: 'Arday Wareejin Kaliyah', path: 'arday-wareejin-kaliyah' },
      { name: 'Diiwangeli Anshax Arday', path: 'diiwangeli-anshax-arday' },
      { name: 'Joojinta Ardayga', path: 'joojinta-ardayga' },
      { name: 'Kala Wareejin Fasalo', path: 'kala-wareejin-fasalo' },
      { name: 'Raadi Arday', path: 'raadi-arday' },
      { name: 'Soo Celi Arday', path: 'soo-celi-arday' },
    ] 
  },
  { name: 'Accounting', icon: Briefcase, path: 'accounting', submenus: [
      { name: 'Account Cusub', path: 'account-cusub' },
      { name: 'Account To Account', path: 'account-to-account' },
      { name: 'BALANCESHEET', path: 'balancesheet' },
      { name: 'Caddeenta Qasnadda', path: 'caddeenta-qasnadda' },
      { name: 'Chart Of Accounts', path: 'chart-of-accounts' },
      { name: 'Income Statement', path: 'income-statement' },
      { name: 'Liiska Qasnadaha', path: 'liiska-qasnadaha' },
      { name: 'Transferred Accounts Report', path: 'transferred-accounts-report' },
      { name: 'TRIAL BALANCE', path: 'trial-balance' },
    ]
  },
  { name: 'Certificates / Cadeymo', icon: Award, path: 'certificates', submenus: [
      { name: 'Generate Certificate', path: 'generate-certificate' },
      { name: 'Certificate Records', path: 'certificate-records' },
    ]
  },
  { name: 'Cusub', icon: PlusCircle, path: 'cusub', submenus: [
      { name: 'Ku Shub Xog Hore', path: 'ku-shub-xog-hore' },
      { name: 'Liiska Ardayda Dhacday', path: 'liiska-ardayda-dhacday' },
      { name: 'Liiska Ardaydii Hore', path: 'past-students' },
      { name: 'La Socodka Casharada Fasalka', path: 'la-socodka-casharada-fasalka' },
      { name: 'Liiska Qalinjabin Taxfitka', path: 'liiska-qalinjabin-taxfitka' },
      { name: 'Liiska La Socodka Casharada Fasa', path: 'liiska-la-socodka-casharada-fasa' },
      { name: 'Q/Mimtixan App', path: 'q-mimtixan-app' },
      { name: 'Q/M imtixan App by Fasal', path: 'q-m-imtixan-app-by-fasal' },
      { name: 'Qalinjabin Taxfitka Arday', path: 'qalinjabin-taxfitka-arday' },
    ]
  },
  { name: 'Diwaangilin', icon: PenSquare, path: 'diwaangilin', submenus: [
      { name: 'Arday Cusub', path: 'diwaangilin-arday-cusub' },
      { name: 'Arday Cusub (Arabic)', path: 'arday-cusub-arabic' },
      { name: 'Arday Cusub (New)', path: 'arday-cusub-new' },
      { name: 'Arday iyo Waalid', path: 'arday-iyo-waalid' },
      { name: 'Diwangelin Xogta Alaabta', path: 'diwangelin-xogta-alaabta' },
      { name: 'Fasal Cusub', path: 'fasal-cusub' },
      { name: 'Hay’ad Cusub', path: 'hayad-cusub' },
      { name: 'Heer Cusub', path: 'heer-cusub' },
      { name: 'Heerka Shaqaalaha', path: 'heerka-shaqaalaha' },
      { name: 'Jago Cusub', path: 'jago-cusub' },
      { name: 'Maado Cusub', path: 'maado-cusub' },
      { name: 'Nuuc Anshax Cusub', path: 'nuuc-anshax-cusub' },
      { name: 'Nuuc Kharaj', path: 'nuuc-kharaj' },
      { name: 'Nuuc Maqnaasho', path: 'nuuc-maqnaasho' },
      { name: 'Nuucyada Bixitaanka Ardayga', path: 'nuucyada-bixitaanka-ardayga' },
      { name: 'Sanad Cusub', path: 'sanad-cusub' },
      { name: 'Shift Cusub', path: 'shift-cusub' },
      { name: 'Shirkad Cusub', path: 'shirkad-cusub' },
      { name: 'Waalid Cusub', path: 'waalid-cusub' },
      { name: 'Xarun Cusub', path: 'xarun-cusub' },
      { name: 'Xarun Fasal 2', path: 'xarun-fasal-2' },
      { name: 'Xiisad Cusub', path: 'xiisad-cusub' },
    ]
  },
  { name: 'Imtixaan Arday', icon: BookOpen, path: 'imtixaan-arday', submenus: [
      { name: 'Natiijo Arday Marksheet', path: 'natiijo-arday-marksheet' },
      { name: 'Back up', path: 'backup' },
      { name: 'Bedel Natiijo', path: 'bedel-natiijo' },
      { name: 'Bedel Natiijo Arday', path: 'bedel-natiijo-arday' },
      { name: 'ID Card', path: 'id-card' },
      { name: 'Imtixaan Wareejin', path: 'imtixaan-wareejin' },
      { name: 'Kala Wareeji Natiijo Maado', path: 'kala-wareeji-natiijo-maado' },
      { name: 'Kashf Imtixaanka', path: 'kashf-imtixaanka' },
      { name: 'Liiska Mudeynta Userada', path: 'liiska-mudeynta-userada' },
      { name: 'Maadooyinka Ugu Liidata', path: 'maadooyinka-ugu-liidata' },
      { name: 'Maadooyinka Ugu Sareeya', path: 'maadooyinka-ugu-sareeya' },
      { name: 'Marksheet v2', path: 'marksheet-v2' },
      { name: 'Marksheet v5', path: 'marksheet-v5' },
      { name: 'Natiijo Daabicid', path: 'natiijo-daabicid' },
      { name: 'Upload Exam', path: 'upload-exam' },
      { name: 'Natiijo Sixid Fasal', path: 'natiijo-sixid-fasal' },
      { name: 'Natiijo Xareyn', path: 'natiijo-xareyn' },
      { name: 'Natiijo Xareyn2', path: 'natiijo-xareyn2' },
      { name: 'Nuuc Imtixaan Cusub', path: 'nuuc-imtixaan-cusub' },
      { name: 'Tir Natijo Fasal', path: 'tir-natijo-fasal' },
    ]
  },
  { name: 'Class Timetable', icon: CalendarDays, path: 'class-timetable', submenus: [
      { name: 'New Timetable', path: 'new-timetable' },
      { name: 'Prepare Subjects', path: 'prepare-subjects' },
      { name: 'Teacher Work Days', path: 'teacher-work-days' },
      { name: 'Create Timetable', path: 'create-timetable' },
      { name: 'Print Timetable', path: 'print-timetable' },
      { name: 'Copy Class Timetable', path: 'copy-class-timetable' },
    ]
  },
  { name: 'Finance', icon: DollarSign, path: 'finance', submenus: [
      { name: 'New Account', path: 'finance-new-account' },
      { name: 'Student Billing (Monthly)', path: 'student-billing-monthly' },
      { name: 'Bus Billing (Monthly)', path: 'bus-billing-monthly' },
      { name: 'Class Billing', path: 'class-billing' },
      { name: 'Journal Entry', path: 'journal-entry' },
      { name: 'Cancel Billing', path: 'cancel-billing' },
      { name: 'Make Payment', path: 'make-payment' },
      { name: 'Collect Cash', path: 'collect-cash' },
      { name: 'Payment Type', path: 'payment-type' },
      { name: 'Student Receipts', path: 'student-receipts' },
      { name: 'Billing Receipts', path: 'billing-receipts' },
      { name: 'Student Payment Statistics', path: 'student-payment-statistics' },
      { name: 'Trial Balance', path: 'finance-trial-balance' },
    ]
  },
  { name: 'Administration', icon: GraduationCap, path: 'administration', submenus: [
      { name: 'Teacher Policy', path: 'teacher-policy' },
      { name: 'Form List', path: 'form-list' },
      { name: 'Teacher Policy List', path: 'teacher-policy-list' },
      { name: 'Graduation Management', path: 'graduation-management' },
      { name: 'Scholarships', path: 'scholarships' },
      { name: 'Attendance System', path: 'attendance-system' },
      { name: 'School Information', path: 'school-information' },
      { name: 'Cancelled Records', path: 'cancelled-records' },
    ]
  },
  { name: 'User Management', icon: User, path: 'user-management', submenus: [
      { name: 'Change Password', path: 'change-password' },
      { name: 'Change Profile Picture', path: 'change-profile-picture' },
      { name: 'Add New User', path: 'add-new-user' },
      { name: 'Update Password', path: 'update-password' },
      { name: 'User List', path: 'user-list' },
      { name: 'User Usage Limits', path: 'user-usage-limits' },
      { name: 'Grant User Permissions', path: 'grant-user-permissions' },
      { name: 'Grant Multiple Permissions', path: 'grant-multiple-permissions' },
      { name: 'Grant Custom Permissions', path: 'grant-custom-permissions' },
      { name: 'Assign User Roles', path: 'assign-user-roles' },
    ]
  },
  { name: 'Human Resource (HRM)', icon: BotMessageSquare, path: 'hrm', submenus: [
      { name: 'Salary Raise', path: 'salary-raise' },
      { name: 'Pay Salary', path: 'pay-salary' },
      { name: 'Monthly Salary Adjustment', path: 'monthly-salary-adjustment' },
      { name: 'Advance Salary', path: 'advance-salary' },
      { name: 'Add New Staff', path: 'add-new-staff' },
      { name: 'Staff Attendance', path: 'staff-attendance' },
      { name: 'Staff Reports', path: 'staff-reports' },
    ]
  },
  { name: 'Reports', icon: BarChart2, path: 'reports', submenus: [
      { name: 'Payment & Collection Summary', path: 'payment-collection-summary' },
      { name: 'Purchase Records', path: 'purchase-records' },
      { name: 'Unpaid Fees Notifications', path: 'unpaid-fees-notifications' },
      { name: 'Failed Student List', path: 'failed-student-list' },
      { name: 'Notifications & Messages', path: 'notifications-messages' },
      { name: 'Staff Messages', path: 'staff-messages' },
      { name: 'Fixed Assets', path: 'fixed-assets' },
      { name: 'Unpaid Student Fees', path: 'unpaid-student-fees' },
      { name: 'Student Payment Records', path: 'student-payment-records' },
      { name: 'Collected Fees Summary', path: 'collected-fees-summary' },
      { name: 'Student List', path: 'student-list' },
      { name: 'Discipline Reports', path: 'discipline-reports' },
      { name: 'Orphan Students', path: 'orphan-students' },
      { name: 'Absent Students', path: 'absent-students' },
      { name: 'Advance Salaries', path: 'advance-salaries' },
      { name: 'Employee List', path: 'employee-list' },
      { name: 'Exam Correction List', path: 'exam-correction-list' },
      { name: 'Exam Types List', path: 'exam-types-list' },
      { name: 'Grade Levels', path: 'grade-levels' },
      { name: 'Attendance Types', path: 'attendance-types' },
      { name: 'Behavior Types', path: 'behavior-types' },
      { name: 'Discounts & Free Fees List', path: 'discounts-free-fees-list' },
      { name: 'Graduation List', path: 'graduation-list' },
      { name: 'Employee Shift List', path: 'employee-shift-list' },
      { name: 'School Branch List', path: 'school-branch-list' },
      { name: 'Class Schedule List', path: 'class-schedule-list' },
      { name: 'SMS Reports', path: 'sms-reports' },
      { name: 'New Cash Register', path: 'new-cash-register' },
      { name: 'Parent Receipts', path: 'parent-receipts' },
      { name: 'Company Records', path: 'company-records' },
      { name: 'Asset Records', path: 'asset-records' },
    ]
  },
  { name: 'Settings', icon: Settings, path: 'settings', submenus: [
      { name: 'Change Language', path: 'change-language' },
      { name: 'Set Default Academic Year', path: 'set-default-academic-year' },
      { name: 'Manage Roles & Permissions', path: 'manage-roles-permissions' },
      { name: 'Backup / Restore Database', path: 'backup-restore-database' },
      { name: 'Update School Info', path: 'update-school-info' },
      { name: 'API Settings', path: 'api-settings' },
      { name: 'Theme Mode', path: 'theme-mode' },
      { name: 'Notification Preferences', path: 'notification-preferences' },
    ]
  },
];

export const BACK4APP_APP_ID = "tHh3lEWxcTQL5FGUhKL7eXqciq80fsYbOT6n7eLi";
export const BACK4APP_REST_KEY = "Vhsvdf8O3QkhCThAwGwvdvylsS7t4wayRlhRbBDU";
export const BACK4APP_API_URL = "https://parseapi.back4app.com/";
